# Introduction to Numpy

### Create a numpy array

In [14]:
import numpy as np
a = np.array([[1,2], [3,4]])
print("The shape of array a is:", a.shape)
print("The type of elements in array a:", a.dtype)

The shape of array a is: (2, 2)
The type of elements in array a: int64


In [31]:
# set random seed to guarantee the reproducibility of your code on different devices
np.random.seed(77)
a = np.random.random((3, 4))
print(a)
b = np.random.random((4, 5))
print(b)

[[0.91910903 0.6421956  0.75371223 0.13931457]
 [0.08731955 0.78800206 0.32615094 0.54106782]
 [0.24023518 0.54542293 0.4005545  0.71519189]]
[[0.83667994 0.58848114 0.29615456 0.28101769 0.70559724]
 [0.42259643 0.05731599 0.74702731 0.45231301 0.17577474]
 [0.049377   0.29247534 0.06679913 0.75115649 0.06377152]
 [0.43190832 0.36417241 0.15197153 0.54671034 0.44329304]]


In [16]:
print(a @ b)

[[0.3533685  0.39482924 0.30466203 0.88714812 0.58607517]
 [0.37367972 0.6517246  0.34650263 0.90884031 0.55173689]
 [0.4947141  0.55631368 0.34061103 0.98832754 0.52045244]]


### Basic Operator of Numpy.array
+ sum (broadcast property)
+ matrix product
+ elementwise product (broadcast property)





#### Broadcasting
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.


![Broadcasting](https://numpy.org/doc/stable/_images/broadcasting_2.png)

In some cases, broadcasting stretches both arrays to form an output array larger than either of the initial arrays.
![Example 2](https://numpy.org/doc/stable/_images/broadcasting_4.png)

# Introduction to Pytorch 

In [4]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

In [11]:
from tensorboardX import SummaryWriter
from torchviz import make_dot

## Torch.Tensor

In [39]:
# define a torch tensor
# even the same random seed in different python package generates different values
torch.manual_seed(77)
a = torch.rand((1000,4))
b = torch.rand((4, 10))
c = torch.rand((10, 50))
d = a @ b @ c
print(d.shape)

torch.Size([1000, 50])


### Convert from `Numpy.array`

In [41]:
np.random.seed(77)
a = np.random.random((3, 4))
print(a)
print(type(a))
print(a.dtype)

print('\n')
# The Torch.tensor has the similar attribute as Numpy.array called `dtype`.
a = torch.tensor(a)
print(a)
print(type(a))
print(a.dtype)


[[0.91910903 0.6421956  0.75371223 0.13931457]
 [0.08731955 0.78800206 0.32615094 0.54106782]
 [0.24023518 0.54542293 0.4005545  0.71519189]]
<class 'numpy.ndarray'>
float64


tensor([[0.9191, 0.6422, 0.7537, 0.1393],
        [0.0873, 0.7880, 0.3262, 0.5411],
        [0.2402, 0.5454, 0.4006, 0.7152]], dtype=torch.float64)
<class 'torch.Tensor'>
torch.float64


False

### Automatic Differentiation
A tensor can be created with `requires_grad=True` so that `torch.autograd` records operations on them for automatic differentiation.

`torch.autograd` provides classes and functions implementing automatic differentiation of arbitrary scalar valued functions. It requires minimal changes to the existing code - you only need to declare Tensor s for which gradients should be computed with the `requires_grad=True` keyword. As of now, we only support autograd for floating point `Tensor` types ( half, float, double and bfloat16) and complex `Tensor` types (cfloat, cdouble).

|Attribute|Description | 
|-|-|
|`backward`|Computes the sum of gradients of given tensors with respect to graph leaves.|
|`grad`|Computes and returns the sum of gradients of outputs with respect to the inputs.|


In [11]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

## Torch.nn
`Torch.nn` module provides large numbers of operators which are the basic building blocks for graphs.
### Linear Layers

|Name| Explanation |
|-|-|
|[`nn.Identity`](https://pytorch.org/docs/stable/generated/torch.nn.Identity.html#torch.nn.Identity)|A placeholder identity operator that is argument-insensitive.|
|[`nn.Linear`](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear)|Applies a linear transformation to the incoming data: $y = x\cdot A^T + b$|
|[`nn.Bilinear`](https://pytorch.org/docs/stable/generated/torch.nn.Bilinear.html#torch.nn.Bilinear)|Applies a bilinear transformation to the incoming data: $y = x_1^TAx_2 + b$ |
|[`nn.LazyLinear`](https://pytorch.org/docs/stable/generated/torch.nn.LazyLinear.html#torch.nn.LazyLinear)|A `torch.nn.Linear` module where *in_features* is inferred.|

### Nonlinear Activations
|Name| Explanation |
|-|-|
|[`nn.ELU`](https://pytorch.org/docs/stable/generated/torch.nn.ELU.html#torch.nn.ELU)|Applies the Exponential Linear Unit (ELU) function, element-wise, as described in the paper: [Fast and Accurate Deep Network Learning by Exponential Linear Units (ELUs)](https://arxiv.org/abs/1511.07289).|
|[`nn.LeakyReLU`](https://pytorch.org/docs/stable/generated/torch.nn.LeakyReLU.html#torch.nn.LeakyReLU)|Applies the element-wise function: $LeakyReLU(X)=\max{(0, x)} + negativeslope * \min{(0, x)}$|
|[`nn.ReLU`](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html#torch.nn.ReLU)|Applies the rectified linear unit function element-wise: $ReLU(x) = (x)^+ = \max{(0, x)}$ |
|[`nn.Sigmoid`](https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html#torch.nn.Sigmoid)|Applies the element-wise function: $\frac{1}{1  + e^{-x}}$ |
### Normalization Layers
|Name| Explanation |
|-|-|
|[`nn.BatchNorm1d`](https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm1d.html#torch.nn.BatchNorm1d)|Applies Batch Normalization over a 2D or 3D input as described in the paper Batch Normalization: [`Accelerating Deep Network Training by Reducing Internal Covariate Shift`](https://arxiv.org/abs/1502.03167) .|

### Loss Functions
|Name| Explanation |
|-|-|
|[`nn.L1Loss`](https://pytorch.org/docs/stable/generated/torch.nn.L1Loss.html#torch.nn.L1Loss)|Creates a criterion that measures the mean absolute error (MAE) between each element in the input $x$ and target $y$.|
|[`nn.MSELoss`](https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html#torch.nn.MSELoss)|Creates a criterion that measures the mean squared error (squared L2 norm) between each element in the input $x$ and target $y$.|
|[`nn.CrossEntropyLoss`](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss)|This criterion computes the cross entropy loss between input logits and target.|


## Torch Optimizer
`torch.optim` is a package implementing various optimization algorithms. Most commonly used methods are already supported, and the interface is general enough, so that more sophisticated ones can also be easily integrated in the future.

### How to use an optimizer
To use `torch.optim` you have to construct an optimizer object that will hold the current state and will update the parameters based on the computed gradients.

### Constructing it
To construct an `Optimizer` you have to give it an iterable containing the parameters (all should be `Variable` s) to optimize. Then, you can specify optimizer-specific options such as the learning rate, weight decay, etc.


![optimization](https://cs231n.github.io/assets/nn3/opt2.gif)
![optimization_methods](https://cs231n.github.io/assets/nn3/opt1.gif)

In [25]:
import torch.optim as optim

W = torch.tensor((3,4))
f = W @ W

optimizer = optim.SGD([W], lr = 0.0001)


# Create your First Neural Network

In [51]:
x = torch.rand((1000, 4))
y = x.pow(2).sum(1)
y.shape


torch.Size([1000])

In [52]:
class MyModel(nn.Module):
    def __init__(self):
        self.W1 = torch.rand((4,5))
        self.b1 = torch.rand((1000))
        self.W2 = torch.rand(5, 10)
        self.b2 = torch.rand((1000))
    def forward(self, x):
        x = self.W1 @ x + self.b1
        x = self.W2 @ x  + self.b2
        return x
model = MyModel()


# Train your First Model

# Visualize a Deep Neural Network

reference link: https://zhuanlan.zhihu.com/p/232348083

running the following command in your terminal after switch to the `./log` folder.
```
tensorboard --logdir=./ 
```

In [13]:
class modelViz(nn.Module):
    def __init__(self):
        super(modelViz, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, 3, 1, padding=1)
        self.bn1 = nn.BatchNorm2d(16)
        self.conv2 = nn.Conv2d(16, 64, 3, 1, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.conv3 = nn.Conv2d(64, 10, 3, 1, padding=1)
        self.bn3 = nn.BatchNorm2d(10)

    def forward(self, x):
        x = self.bn1(self.conv1(x))
        x = F.relu(x)
        x = self.bn2(self.conv2(x))
        x = F.relu(x)
        x = self.bn3(self.conv3(x))
        x = F.relu(x)
        return x

modelviz = modelViz()
# 创建输入
sampledata = torch.rand(1, 3, 4, 4)
# 看看输出结果对不对
out = modelviz(sampledata)
# print(out)  # 测试有输出，网络没有问题




# 1. 来用tensorflow进行可视化
with SummaryWriter("./log", comment="sample_model_visualization") as sw:
    sw.add_graph(modelviz, sampledata)
torch.save(modelviz, "./log/modelviz.pt")

tensor([[[[0.0000, 0.0000, 0.0000, 0.6836],
          [0.0000, 0.3555, 0.4327, 0.1902],
          [0.0000, 1.1358, 1.7973, 2.0034],
          [0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 2.1114, 0.0000, 0.3716],
          [0.5349, 0.0000, 0.0000, 2.2730],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.2119, 0.0000, 0.1004, 0.2430]],

         [[0.2611, 0.0000, 0.0574, 0.0000],
          [1.0215, 0.0000, 0.0000, 0.1554],
          [0.9703, 1.9999, 0.4493, 0.0000],
          [0.6199, 1.0380, 0.0000, 0.0000]],

         [[0.6803, 0.1997, 0.1155, 0.1446],
          [1.6370, 0.3171, 0.0000, 0.0000],
          [1.2820, 0.8807, 0.9972, 0.0000],
          [0.6175, 0.0000, 0.0000, 0.0000]],

         [[0.2061, 0.0000, 0.0000, 0.0000],
          [0.4912, 1.5697, 0.5438, 0.4003],
          [0.0000, 1.0927, 1.3977, 1.3004],
          [0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.2109, 0.4041],
          [1.3927, 0.0000, 0.1822, 0.0000],
          [0.2164, 0.0