# Introduction to Numpy

In [1]:
import numpy as np

In [15]:
np.random.seed(2)
a = np.random.random((3, 4))
print(a)
b = np.random.random((4, 5))
print(b)

[[0.4359949  0.02592623 0.54966248 0.43532239]
 [0.4203678  0.33033482 0.20464863 0.61927097]
 [0.29965467 0.26682728 0.62113383 0.52914209]]
[[0.13457995 0.51357812 0.18443987 0.78533515 0.85397529]
 [0.49423684 0.84656149 0.07964548 0.50524609 0.0652865 ]
 [0.42812233 0.09653092 0.12715997 0.59674531 0.226012  ]
 [0.10694568 0.22030621 0.34982629 0.46778748 0.20174323]]


In [16]:
print(a @ b)

[[0.3533685  0.39482924 0.30466203 0.88714812 0.58607517]
 [0.37367972 0.6517246  0.34650263 0.90884031 0.55173689]
 [0.4947141  0.55631368 0.34061103 0.98832754 0.52045244]]


# Introduction to Pytorch 

In [10]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

In [11]:
from tensorboardX import SummaryWriter
from torchviz import make_dot

# Visualize a Deep Neural Network

reference link: https://zhuanlan.zhihu.com/p/232348083

In [13]:
class modelViz(nn.Module):
    def __init__(self):
        super(modelViz, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, 3, 1, padding=1)
        self.bn1 = nn.BatchNorm2d(16)
        self.conv2 = nn.Conv2d(16, 64, 3, 1, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.conv3 = nn.Conv2d(64, 10, 3, 1, padding=1)
        self.bn3 = nn.BatchNorm2d(10)

    def forward(self, x):
        x = self.bn1(self.conv1(x))
        x = F.relu(x)
        x = self.bn2(self.conv2(x))
        x = F.relu(x)
        x = self.bn3(self.conv3(x))
        x = F.relu(x)
        return x

modelviz = modelViz()
# 创建输入
sampledata = torch.rand(1, 3, 4, 4)
# 看看输出结果对不对
out = modelviz(sampledata)
# print(out)  # 测试有输出，网络没有问题

# 1. 来用tensorflow进行可视化
with SummaryWriter("./log", comment="sample_model_visualization") as sw:
    sw.add_graph(modelviz, sampledata)
torch.save(modelviz, "./log/modelviz.pt")

tensor([[[[0.0000, 0.0000, 0.0000, 0.6836],
          [0.0000, 0.3555, 0.4327, 0.1902],
          [0.0000, 1.1358, 1.7973, 2.0034],
          [0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 2.1114, 0.0000, 0.3716],
          [0.5349, 0.0000, 0.0000, 2.2730],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.2119, 0.0000, 0.1004, 0.2430]],

         [[0.2611, 0.0000, 0.0574, 0.0000],
          [1.0215, 0.0000, 0.0000, 0.1554],
          [0.9703, 1.9999, 0.4493, 0.0000],
          [0.6199, 1.0380, 0.0000, 0.0000]],

         [[0.6803, 0.1997, 0.1155, 0.1446],
          [1.6370, 0.3171, 0.0000, 0.0000],
          [1.2820, 0.8807, 0.9972, 0.0000],
          [0.6175, 0.0000, 0.0000, 0.0000]],

         [[0.2061, 0.0000, 0.0000, 0.0000],
          [0.4912, 1.5697, 0.5438, 0.4003],
          [0.0000, 1.0927, 1.3977, 1.3004],
          [0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.2109, 0.4041],
          [1.3927, 0.0000, 0.1822, 0.0000],
          [0.2164, 0.0